jobs:
  include:
    - stage: functionality
      language: python
      sudo: required
      services:
        - docker
      env:
        - CODALAB_USERNAME=codalab CODALAB_PASSWORD=testpassword CI=false CODALAB_SERVICE_HOME=/home/travis/codalab/home/ CODALAB_BUNDLE_STORE=/home/travis/codalab/bundles/ CODALAB_MYSQL_MOUNT=/home/travis/codalab/mysql/
      python: 2.7
      before_install:
        - docker --version
      install:
        - pip install --upgrade pip docker-compose
      before_script:
        - ./docker/service/start-service.sh -i -b
        - pip install ./worker
        - cl-worker --server http://127.0.0.1:2900 --work-dir /home/travis/.codalab/worker-scratch --password-file /home/travis/.codalab/root.password --verbose &
      script:
        - ./venv/bin/python test-cli.py --cl-executable codalab/bin/cl default
    - stage: style
      language: python
      python: 3.6
      install: pip install --upgrade black==18.9b0
      script: black . --check
    - stage: deploy
      script: echo "Deploying"
      language: python
      sudo: required
      services:
        - docker
      env:
        - CODALAB_USERNAME=codalab CODALAB_PASSWORD=testpassword CI=false
      python: 2.7
      after_success: echo "skipped"
      before_deploy:
        - pip install twine
      deploy:
        # Build docker images using tag if it's a version tag (we're releasing)
        # Otherwise if we're on master or staging build named images
        - provider: script
          # Remove first char of tag (v) to get version number from tag
          script: ./scripts/travis-deploy.sh ${TRAVIS_TAG#?} release
          on:
            # only build on valid semver tags
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
        - provider: script
          # Build with branch name if not releasing
          script: ./scripts/travis-deploy.sh $TRAVIS_BRANCH branch
          on:
            # only build for master and staging for debugging
            branch: master
