version: '3'

services:
  frontend:
    image: codalab/frontend:local-dev
    ports:
      - 2700:2700

  nginx:
    image: nginx:1.12.0
    command: /data/bin/wait-for-it.sh rest-server:2900 -- nginx
    ports:
      - 80:80
    volumes:
      - ./files/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh
