version: '3.5'

x-codalab-home-mount:
  &codalab-home-mount
  type: bind
  source: ${CODALAB_SERVICE_HOME}
  target: ${CODALAB_SERVICE_HOME}

x-codalab-bundles-mount:
  &codalab-bundles-mount
  type: bind
  source: ${CODALAB_BUNDLE_STORE}
  target: ${CODALAB_BUNDLE_STORE}

x-non-blocking-logging:
  &non-blocking-logging
  driver: json-file
  options:
    mode: non-blocking

services:
  mysql:
    image: mysql:5.5.53
    environment:
      - MYSQL_ROOT_PASSWORD=${CODALAB_MYSQL_ROOT_PWD}
      - MYSQL_DATABASE=codalab_bundles
      - MYSQL_USER=${CODALAB_MYSQL_USER}
      - MYSQL_PASSWORD=${CODALAB_MYSQL_PWD}
    volumes:
      - ${CODALAB_MYSQL_MOUNT}/config/conf.d:/etc/mysql/conf.d
      - ${CODALAB_MYSQL_MOUNT}/mysql:/var/lib/mysql
    ports:
      - ${CODALAB_MYSQL_PORT}:3306
    logging:
      *non-blocking-logging

  rest-server:
    image: codalab/bundleserver:${CODALAB_VERSION}
    command: server
    ports:
      - ${CODALAB_REST_PORT}:2900
    environment:
      - CODALAB_HOME=${CODALAB_SERVICE_HOME}
      - CODALAB_USERNAME=${CODALAB_ROOT_USER}
      - CODALAB_PASSWORD=${CODALAB_ROOT_PWD}
    volumes:
      - *codalab-home-mount
      - *codalab-bundles-mount
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh
    depends_on:
      - mysql
    logging:
      *non-blocking-logging

  bundle-manager:
    image: codalab/bundleserver:${CODALAB_VERSION}
    command: bundle-manager
    environment:
      - CODALAB_HOME=${CODALAB_SERVICE_HOME}
      - CODALAB_USERNAME=${CODALAB_ROOT_USER}
      - CODALAB_PASSWORD=${CODALAB_ROOT_PWD}
    volumes:
      - *codalab-home-mount
      - *codalab-bundles-mount
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh
    depends_on:
      - rest-server
    logging:
      *non-blocking-logging

  frontend:
    image: codalab/frontend:${CODALAB_VERSION}
    ports:
      - ${CODALAB_FRONTEND_PORT}:2700
    depends_on:
      - rest-server
    logging:
      *non-blocking-logging

  nginx:
    image: nginx:1.12.0
    command: /data/bin/wait-for-it.sh rest-server:2900 -- nginx
    ports:
      - 80:80
    volumes:
      - ./files/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh
    depends_on:
      - frontend
    logging:
      *non-blocking-logging

  worker:
    image: codalab/worker:${CODALAB_VERSION}
    command: --server http://rest-server:2900 --verbose --work-dir ${CODALAB_WORKER_DIR}
    privileged: True
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CODALAB_WORKER_DIR}:${CODALAB_WORKER_DIR}
    environment:
      - CODALAB_USERNAME=${CODALAB_ROOT_USER}
      - CODALAB_PASSWORD=${CODALAB_ROOT_PWD}
    depends_on:
      - bundle-manager
    logging:
      *non-blocking-logging

  tests:
    image: codalab/bundleserver:${CODALAB_VERSION}
    working_dir: /opt/codalab-worksheets/
    entrypoint: ./venv/bin/python ./test-cli.py
    command: all --instance http://rest-server:2900
    environment:
      - CODALAB_USERNAME=${CODALAB_ROOT_USER}
      - CODALAB_PASSWORD=${CODALAB_ROOT_PWD}
    depends_on:
      - rest-server
    logging:
      *non-blocking-logging
